// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nwowzgmtmjqczlyzgsnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im53b3d6Z210bWpxY3pseXpnc25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTU1NjgsImV4cCI6MjA2NTA3MTU2OH0.coCtCINm_rwx27PkwuvijCUH2SxWvR17wohXrUaXpv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});